### ISSUE TITLE
Test assertion/case unification

### ISSUE THREAD

**Issue by drew887** [ryuuji3/test-decorators#1]
Even just looking at your example the seperation of case and assertion seems pretty tedious and verbose

```
@TestCase(1, 1) 
@TestAssertion(2) 
@TestCase(2, 2)
@TestAssertion(4)
```

Is there anyway to have case take a final or maybe first parameter as the expected assertion?

**Comment by ryuuji3** [comment]
I agree, it's a little verbose. 
It might look like this;
```ts
@TestCase(1, 1, 2)
@TestCase(2, 1, 1)
```
However I think that's equally confusing. How about...
```ts
// @TestCase(param: any[], result: any)
@TestCase([1, 1], 2)
```

Or I can accept an object for readability. I'm voting for this one.
```ts
// @TestCase({params: any[], result: any})
@TestCase({ params: [1, 1], result: 2 })
```

**Comment by drew887** [comment]
Objects sound pretty great

**Comment by ryuuji3** [comment]
Then, I'll make an interface;
```
interface TestAssertionI {
   params?: any[],
   result : () => any
}
```
Example:
```tsc
let assertion1 = { 
  params: [1, 1],
  result => 2
}

@TestCase(assertion1)
```

Thanks!

**Comment by ryuuji3** [comment]
Actually, it's even better than I thought. I forgot that I'll need to test for more than equality. I'm updating the interface to have a bunch of different assertion types; equals, isGreaterThan, isLessThan, throws, etc.
